### PR TITLE
Separating_properties

### LINKED ISSUE #16: Support for averaging and sample time register
I'm trying to prototype a musical application with the CAP1188 but the latency on a touch is slightly too long at the default setting. It would be good if the library provided getters and setters for the "AVERAGING AND SAMPLING CONFIGURATION REGISTER" so that the sample time can be adjusted or reduced.

### PR DESCRIPTION
**Pull request by jposada202020**
Solves #16

### CODE REVIEW

**Comment by ladyada** [comment]
hihi have you tested this on hardware?

**Comment by jposada202020** [comment]
No, I wish, flying blind here, the deal is I do the changes, @dherrada test :) see PR #17

**Comment by evaherrada** [comment]
Oh yah, I said I would test. Will do after I release some stuff

**Comment by jposada202020** [comment]
Ok I add a new example.  You could use the example included to test. @ladyada or @dherrada ? maybe :) Thank you!!

## Expected Results:
```python
Adafruit CircuitPython 6.2.0 on 2021-04-05; Adafruit Feather RP2040 with rp2040
>>> import cap1188_simpletest
Sensor Initial Congfiguration Values: 128
Setting Up Averages
Average: 1
Average: 2
Average: 4
Average: 8
Average: 16
Average: 32
Average: 64
Average: 128
Setting Up Samples
Sample: 320us
Sample: 640us
Sample: 1.28ms
Sample: 2.56ms
Setting Up Samples
Cycle: 35ms
Cycle: 70ms
Cycle: 105ms
Cycle: 140ms
Done!
```

**Review by evaherrada — APPROVED** [review]
Looks good to me. Thanks for testing!

**Comment by jposada202020** [comment]
Thank you... :)

**Pull request merged**
